version: '3.8'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: counterdb
      POSTGRES_USER: counteruser
      POSTGRES_PASSWORD: counterpass
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  counter-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/counterdb
      - SPRING_DATASOURCE_USERNAME=counteruser
      - SPRING_DATASOURCE_PASSWORD=counterpass

volumes:
  postgres-data: